# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'music 2' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for music 2
pod 'Google-Mobile-Ads-SDK'

  target 'music 2Tests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'music 2UITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
